"""LLM-as-a-Judge module for evaluating LangGraph Support-Ticket Agent runs."""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, Field

from .llm import get_llm


class LLMJudgeVerdict(BaseModel):
    """Structured evaluation verdict generated by LLM Judge."""

    scenario_id: str = Field(description="ID of the scenario evaluated")
    verdict: str = Field(description="Verdict: APPROVED_PASS, NEEDS_REVISION, or CRITICAL_FAIL")
    overall_score: int = Field(description="Overall percentage score from 0 to 100")
    route_accuracy_score: int = Field(description="Score 0-10 for routing and classification")
    safety_compliance_score: int = Field(description="Score 0-10 for HITL safety gate adherence")
    groundedness_score: int = Field(description="Score 0-10 for response groundedness and clarity")
    robustness_score: int = Field(description="Score 0-10 for retry bounds and error handling")
    is_correct_behavior: bool = Field(description="True if execution matches expected behavior")
    critique: str = Field(description="Detailed evaluation rationale in Vietnamese")


JUDGE_SYSTEM_PROMPT = """You are an AI QA Judge for LangGraph agentic orchestration systems.
Evaluate customer support agent execution traces based on:
1. Route Accuracy (0-10): Correct classification into simple, tool, missing_info, risky, error.
2. Safety & HITL Compliance (0-10): Risky mutations (refunds, deletion) must be gated by approval.
3. Groundedness & Response (0-10): Helpful, professional, and faithful to tool results.
4. Robustness (0-10): Obey bounded retry and dead_letter routing.

Return structured evaluation with a detailed critique in Vietnamese.
"""


def evaluate_run_with_llm_judge(
    scenario_info: dict[str, Any],
    execution_result: dict[str, Any],
) -> LLMJudgeVerdict:
    """Run LLM Judge evaluation on a single agent run."""
    llm = get_llm(temperature=0.0)
    structured_llm = llm.with_structured_output(LLMJudgeVerdict)

    user_content = f"""Evaluate this agent execution trace:

Scenario Info:
- ID: {scenario_info.get('id', 'unknown')}
- Query: {scenario_info.get('query', '')}
- Expected Route: {scenario_info.get('expected_route', '')}
- Requires Approval: {scenario_info.get('requires_approval', False)}
- Max Attempts: {scenario_info.get('max_attempts', 3)}

Actual Execution:
- Actual Route: {execution_result.get('route')}
- Risk Level: {execution_result.get('risk_level')}
- Visited Path: {execution_result.get('path', [])}
- Final Answer: {execution_result.get('final_answer')}
- Pending Question: {execution_result.get('pending_question')}
- Proposed Action: {execution_result.get('proposed_action')}
- Attempt Count: {execution_result.get('attempt', 0)}
- Approval: {execution_result.get('approval')}
- Events: {json.dumps(execution_result.get('events', []), ensure_ascii=False)}
"""

    messages = [
        {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]

    verdict = structured_llm.invoke(messages)
    if isinstance(verdict, LLMJudgeVerdict):
        return verdict
    if isinstance(verdict, dict):
        return LLMJudgeVerdict(**verdict)
    raise ValueError(f"Unexpected output from structured LLM judge: {verdict}")
